openapi: 3.0.0
info:
  title: Gravitate Health Focusing Interface
  version: 0.0.1
  description: Interface detailing the methods available for focusing
  contact:
    name: Álvaro Belmar
    email: abelmar@lst.tfo.upm.es
paths:
  /med-information-focus:
    post:
      tags:
        - Medication Information Focusing
      responses:
        '200':
          description: Medication Information Focusing endpoint
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MedInformationBundle'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MedInformationBundle'
servers:
  - url: http://127.0.0.1:3000
components:
  schemas:
    MedInformation:
      title: MedInformation
      type: object
      properties:
        id:
          type: number
        identifier:
          type: string
        code: {}
        status:
          type: string
        marketingAuthorizationHolder: {}
        doseForm: {}
        totalVolume: {}
        ingredient: 
          type: array
          items:
            type: object
        batch: {}
      required:
        - id
        - identifier
        - status
      additionalProperties: false
    MedInformationBundle:
      title: MedInformationBundle
      allOf:
        - $ref: '#/components/schemas/MedInformation'
        - type: object
          properties:
            IPS: 
              type: object
      additionalProperties: false